# Generated by Django 5.0.6 on 2024-06-01 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(db_index=True, max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('Surname', models.CharField(max_length=20)),
                ('img', models.ImageField(null=True, upload_to='images/')),
                ('age', models.IntegerField()),
                ('id_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='announ.account')),
            ],
        ),
        migrations.CreateModel(
            name='announmodel',
            fields=[
                ('about', models.CharField(default='Описание отсутствует', max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(null=True, upload_to='images/')),
                ('value', models.IntegerField()),
                ('id_account', models.IntegerField()),
                ('id_announ', models.AutoField(primary_key=True, serialize=False)),
                ('announ_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announ.cate')),
            ],
        ),
    ]
