# Generated by Django 5.0.6 on 2024-06-02 13:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('surname', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('img', models.ImageField(default='needimages/defaultimage.png', null=True, upload_to='images/')),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='announmodel',
            fields=[
                ('about', models.CharField(default='Описание отсутствует', max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(null=True, upload_to='images/')),
                ('value', models.IntegerField()),
                ('id_announ', models.AutoField(primary_key=True, serialize=False)),
                ('announ_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='our_models.cate')),
                ('id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='our_models.profile')),
            ],
        ),
    ]
