# Generated by Django 5.0.4 on 2024-06-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_models', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='surname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
